[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = "./"}]
libs = ["lib"]
out = "out"
# solc_version = "0.8.30"
src = "src"
test = "test"
via_ir = true
optimizer = true
optimizer_runs = 10000


[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
